pipeline {
    agent { label 'slave2' }

    environment {
        NEXUS_URL      = "http://nexus:8081"
        NEXUS_REPO     = "maven-releases"
        ARTIFACT_PATH  = "com/vacancy/my-app-devops-ex/0.0.2/my-app-devops-ex-0.0.2.jar"
        ARTIFACT_LOCAL = "app.jar"
        ANSIBLE_CONTAINER = "ansible"
    }

    stages {
        stage('Download artifact from Nexus') {
            steps {
                sh """
                    echo "Downloading artifact from Nexus..."
                    curl -f -L -u admin:ТВОЙ_ПАРОЛЬ \
                      ${NEXUS_URL}/repository/${NEXUS_REPO}/${ARTIFACT_PATH} \
                      -o ${ARTIFACT_LOCAL}
                    ls -lh ${ARTIFACT_LOCAL}
                """
            }
        }

        stage('Copy artifact into ansible container') {
            steps {
                sh """
                    echo "Copy JAR into ansible container..."
                    docker cp ${ARTIFACT_LOCAL} ${ANSIBLE_CONTAINER}:/ansible/app.jar
                """
            }
        }

        stage('Run ansible playbook') {
            steps {
                sh """
                    echo "Run Ansible playbook inside ansible container..."
                    docker exec ${ANSIBLE_CONTAINER} bash -lc 'cd /ansible && ansible-playbook -i inventory/hosts playbook.yml'
                """
            }
        }
    }
}
